var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "  xxxx                                                                          ",
   "  x                                                                             ",
   "  x                                    o                                        ",
   "  x                                    x    xxxxxxxxx xxxxxxxx                  ",
   "  x                       o         x       x                x                  ",
   "  x                o                        x        o       x                  ",
   "  x @         c   xx    x   x   x           x        x       x                  ",
   "  xxxxxx     xxx        x!!!x               x                x       xxxxxxxxxxx",
   "  x                    sxxxxx               x                x       x          ",
   "  x                    sx                   x        x       x       x       oo ",
   "  x                    xx                   x                x       x       xxx",
   "  x                                         x                x       xx  x  x   ",
   "  x  o                                      x        x       x       x   x      ",
   "  x ooo                                     x                        x   x      ",
   "  x  o    c                                 x                        x  xx      ",
   "  xxxxxxxxxxxxoxxxxxxxxxxxxx      xxxxxx  xxxxx  xxxxx     xxxxxxx   x   xxxxx  ",
   "             xsx           xssssssx    x         x   x     x     x   x   x      ",
   "             x x           xssssssx    x        xx   x!!!!!x     x  xxx  x      ",
   "             x x           xssssssx    x         x   x!!!!!x     x       x      ",
   "             x!x           xxxxxxxx    x x   c   x   xxxxxxx     x       x      ",
   "             xxx                       xxxxxxxxxxx               xxxxxxxxx      ",
   "                                                                                "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                             x                                                 ",
   "                                             x               x                                                  ",
   "                                             x             oox                                                  ",
   "                x                            x x       xxxxxxx                                                          ",
   "              x ! x                          x        x                                                           ",
   "                x                            x x       x                                                          ",
   "                                             x        x                                                         ",
   "x    xxxxxxx    x                            x        x                                                                 ",
   "     xx    x    x       = = = =            oox x       x                                                                     ",
   "o   xxx    x    xxxxxxxxxx!!xxxxxxxxxxxxxxxxxx        x                                                                                         ",
   "x    xx    x             xxxx                        x                                                               ",
   "     xx    x        o          =       =              x                                                             ",
   "     xx    x   xxxxxxxx            =                 x                                                                   ",
   "x    xx    x    x     x   xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                        ",
   "    xxx    x    x     x                                                                                            ",
   " @   xx    x    x     xx  xxxxxxx                                                                                          ",
   "xxxxxxx    x    x      x    oooox                                                                                  ",
   "xxxxxxx    x!!!!x      xxxxxxxxxx                                                                                                  ",
   "xxxxxxx    x!!!!x                                                                                                        ",
   "xxxxxxx    xxxxxx                                                                                                        ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                             o                                                 ",
   "                                     xxx     x       x       x                                                      ",
   "                              xx                                                                                ",
   "                         o x                                                                                    ",
   "                        xxx                                                                                      ",
   "                                                                                                              ",
   "                    xxx                                                                                          ",
   "           =   =      x                                                                                            ",
   "              xxx                                                                                                ",
   "   xxxxx               = = =x                                                                                             ",
   "  o  o x                                                                                                        ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                                        ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                      o             o  ooo   oo    o  oo    o  oooooo  oooooo                                 ",
   "                       o     o     o   ooo   o o   o  o o   o  o       o     o                                ",
   "                        o   o o   o          o  o  o  o  o  o  oooo    oooooo                                 ",
   "                         o o   o o      o    o   o o  o   o o  o       o    o                                 ",
   "                          o     o       o    o    oo  o    oo  oooooo  o     o                                ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                         xxxxxxxxx     xxx   xxxxxxx  xxxxxxx  xxxxxx  xxxxxxxx                               ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
